// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Planet is the predicate function for planet builders.
type Planet func(*sql.Selector)
